import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { ToolDeps } from './get-comments-tool.js';
import { registerGetCommentsTool } from './get-comments-tool.js';
import { registerSummarizeCommentsTool } from './summarize-comments-tool.js';
import { registerFindThreadsTool } from './find-threads-tool.js';
import { registerGetMetadataTool } from './get-metadata-tool.js';
import { registerGetFigjamTool } from './get-figjam-tool.js';
import { registerGetScreenshotTool } from './get-screenshot-tool.js';
import { registerGetVariablesTool } from './get-variables-tool.js';
import { registerGetDesignContextTool } from './get-design-context-tool.js';
import { registerSearchDesignSystemTool } from './search-design-system-tool.js';
import { registerGetLibrariesTool } from './get-libraries-tool.js';
import { registerGetCodeConnectMapTool } from './get-code-connect-map-tool.js';
import { registerExportAssetsTool } from './export-assets-tool.js';
import { registerWriteCommentsTools } from './write-comments-tools.js';
import { registerFindNodesTool } from './find-nodes-tool.js';
import { registerGetTextStylesTool } from './get-text-styles-tool.js';
import { registerCompareBreakpointsTool } from './compare-breakpoints-tool.js';
import { registerGetReviewBoardTool } from './get-review-board-tool.js';
import { registerGetPinDetailTool } from './get-pin-detail-tool.js';
import { registerGetLayoutSpecTool } from './get-layout-spec-tool.js';
import { registerGetViewTool } from './get-view-tool.js';
import { registerSuggestPairsTool } from './suggest-pairs-tool.js';
import { registerCompareNodeToDomTool } from './compare-node-to-dom-tool.js';
import { registerCompareDomToDomTool } from './compare-dom-to-dom-tool.js';
import { registerFindBreakpointVariantTool } from './find-breakpoint-variant-tool.js';
import { registerGetNodeAncestryTool } from './get-node-ancestry-tool.js';

export function registerAllTools(server: McpServer, deps: ToolDeps): void {
  registerGetCommentsTool(server, deps);
  registerSummarizeCommentsTool(server, deps);
  registerFindThreadsTool(server, deps);
  registerGetMetadataTool(server, deps);
  registerFindNodesTool(server, deps);
  registerGetTextStylesTool(server, deps);
  registerCompareBreakpointsTool(server, deps);
  registerGetLayoutSpecTool(server, deps);
  registerGetViewTool(server, deps);
  registerSuggestPairsTool(server, deps);
  registerCompareNodeToDomTool(server, deps);
  registerCompareDomToDomTool(server, deps);
  registerFindBreakpointVariantTool(server, deps);
  registerGetNodeAncestryTool(server, deps);
  registerGetReviewBoardTool(server, deps);
  registerGetPinDetailTool(server, deps);
  registerGetFigjamTool(server, deps);
  registerGetScreenshotTool(server, deps);
  registerGetVariablesTool(server, deps);
  registerGetDesignContextTool(server, deps);
  registerSearchDesignSystemTool(server, deps);
  registerGetLibrariesTool(server, deps);
  registerGetCodeConnectMapTool(server, deps);
  registerExportAssetsTool(server, deps);
  registerWriteCommentsTools(server, deps);
}
